### ISSUE TITLE
このリポジトリは今後メンテナンスされない予定ですか？

### ISSUE THREAD

**Issue by sseiichi** [unity3d-jp/Project_TCC#6]
Nobuyuki KobayashiさんがUnity Technologies Japanを退職されたとSNSで報告されていますが、今後このソフトは更新されないのでしょうか？

**Comment by sindharta-tanuwijaya** [comment]
お問い合わせいただき、ありがとうございます。

[ルートのページ](https://github.com/unity3d-jp/Project_TCC)にも書いてありますが、
```
This project and repository "Project_TCC" is provided as-is, without any maintenance or release plan.
```
Project_TCC は今後メンテされる予定はないです。
どうぞよろしくお願い致します。

**Comment by sseiichi** [comment]
了解しました。ありがとうございます。
英語で書かれていたんですね。てっきり日本語の文章と同じことが書かれているのかと思って見落としていました。申し訳ありません。

**Comment by sindharta-tanuwijaya** [comment]
いえいえ。とんでもないです。
それでは、この issue をクローズします。
どうぞよろしくお願い致します。
